/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XxYXDMPfugw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Image from "next/image"

export function Banner() {
  return (
    <section className="w-full">
      <div className="relative h-[50vh] sm:h-[60vh] md:h-[70vh] lg:h-[80vh] xl:h-[90vh]">
        <img
          src="/images.png"
          alt="Banner Image"
          fill
          className="object-cover"
          width="1920"
          height="1080"
          style={{ aspectRatio: "1920/720", objectFit: "cover" }}
        />
      </div>
    </section>
  )
}
