/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GmIniaU0E1b
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

export function BannerPerfil() {
  return (
    <Card className="w-full rounded-2x2 overflow-hidden">
      <div className="h-70 bg-[#1e1e1e] relative flex justify-center">
        <img
          src="/placeholder.svg"
          alt="Banner"
          className="w-full h-full object-cover"
          width="768"
          height="192"
          style={{ aspectRatio: "768/192", objectFit: "cover" }}
        />
        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-[#1e1e1e]" />
      </div>
      <div className="p-6 pt-12 bg-white text-black">
        <div className="flex items-center gap-4">
          <Avatar className="w-24 h-24 border-4 border-white">
            <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
            <AvatarFallback>MS</AvatarFallback>
          </Avatar>
          <div className="flex-1">
            <div className="text-2xl font-bold">Ms Grande</div>
            <div className="text-sm text-gray-500">ms@example.com</div>
          </div>
        </div>
        <div className="mt-4 space-y-2">
          <div className="flex items-center gap-2">
            <MapPinIcon className="w-4 h-4 text-gray-500" />
            <span className="text-gray-500">New York, USA</span>
          </div>
          <div className="flex items-center gap-2">
            <InfoIcon className="w-4 h-4 text-gray-500" />
            <span>Im a software engineer with a passion for building beautiful and functional web applications.</span>
          </div>
        </div>
      </div>
    </Card>
  )
}

function InfoIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}


function MapPinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}
