/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/218BFKhOJoU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { JSX, SVGProps, useState } from "react"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"

export function Carrito() {
  const [quantities, setQuantities] = useState([1, 2, 1])
  const handleQuantityChange = (index: number, value: number) => {
    const newQuantities = [...quantities]
    newQuantities[index] = value
    setQuantities(newQuantities)
  }
  return (
    <div className="container mx-auto px-4 md:px-6 py-8 sm:px-2 lg:px-8">
      <header className="mb-8">
        <h1 className="text-2xl font-bold">Carrito de compras</h1>
      </header>
      <div className="grid md:grid-cols-[1fr_300px] gap-8 sm:grid-cols-1 lg:grid-cols-[1fr_400px]">
        <div className="space-y-6">
          <div className="grid grid-cols-[80px_1fr_80px] items-center gap-4 border-b pb-4 sm:grid-cols-[60px_1fr_60px] lg:grid-cols-[100px_1fr_100px]">
            <img
              src="/placeholder.svg"
              alt="Producto"
              width={80}
              height={80}
              className="rounded-md object-cover sm:w-[60px] sm:h-[60px] lg:w-[100px] lg:h-[100px]"
              style={{ aspectRatio: "80/80", objectFit: "cover" }}
            />
            <div>
              <h3 className="font-medium">Camiseta de Algodón</h3>
              <p className="text-sm text-muted-foreground">Color: Negro</p>
            </div>
            <div className="flex items-center gap-2">
              <Button size="icon" variant="outline" onClick={() => handleQuantityChange(0, quantities[0] - 1)}>
                <MinusIcon className="h-4 w-4" />
              </Button>
              <span>{quantities[0]}</span>
              <Button size="icon" variant="outline" onClick={() => handleQuantityChange(0, quantities[0] + 1)}>
                <PlusIcon className="h-4 w-4" />
              </Button>
            </div>
          </div>
          <div className="grid grid-cols-[80px_1fr_80px] items-center gap-4 border-b pb-4 sm:grid-cols-[60px_1fr_60px] lg:grid-cols-[100px_1fr_100px]">
            <img
              src="/placeholder.svg"
              alt="Producto"
              width={80}
              height={80}
              className="rounded-md object-cover sm:w-[60px] sm:h-[60px] lg:w-[100px] lg:h-[100px]"
              style={{ aspectRatio: "80/80", objectFit: "cover" }}
            />
            <div>
              <h3 className="font-medium">Pantalones Vaqueros</h3>
              <p className="text-sm text-muted-foreground">Talla: 32</p>
            </div>
            <div className="flex items-center gap-2">
              <Button size="icon" variant="outline" onClick={() => handleQuantityChange(1, quantities[1] - 1)}>
                <MinusIcon className="h-4 w-4" />
              </Button>
              <span>{quantities[1]}</span>
              <Button size="icon" variant="outline" onClick={() => handleQuantityChange(1, quantities[1] + 1)}>
                <PlusIcon className="h-4 w-4" />
              </Button>
            </div>
          </div>
          <div className="grid grid-cols-[80px_1fr_80px] items-center gap-4 border-b pb-4 sm:grid-cols-[60px_1fr_60px] lg:grid-cols-[100px_1fr_100px]">
            <img
              src="/placeholder.svg"
              alt="Producto"
              width={80}
              height={80}
              className="rounded-md object-cover sm:w-[60px] sm:h-[60px] lg:w-[100px] lg:h-[100px]"
              style={{ aspectRatio: "80/80", objectFit: "cover" }}
            />
            <div>
              <h3 className="font-medium">Zapatillas Deportivas</h3>
              <p className="text-sm text-muted-foreground">Talla: 42</p>
            </div>
            <div className="flex items-center gap-2">
              <Button size="icon" variant="outline" onClick={() => handleQuantityChange(2, quantities[2] - 1)}>
                <MinusIcon className="h-4 w-4" />
              </Button>
              <span>{quantities[2]}</span>
              <Button size="icon" variant="outline" onClick={() => handleQuantityChange(2, quantities[2] + 1)}>
                <PlusIcon className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>
        <div className="bg-muted/40 rounded-md p-6 space-y-4 sm:mt-4 lg:mt-0">
          <div className="flex justify-between">
            <span>Subtotal</span>
            <span className="font-medium">
              ${(149.97 * quantities[0] + 149.97 * quantities[1] + 149.97 * quantities[2]).toFixed(2)}
            </span>
          </div>
          <div className="flex justify-between">
            <span>Envío</span>
            <span className="font-medium">$5.00</span>
          </div>
          <Separator />
          <div className="flex justify-between items-center">
            <span className="text-lg font-medium">Total</span>
            <span className="text-lg font-medium">
              ${(149.97 * quantities[0] + 149.97 * quantities[1] + 149.97 * quantities[2] + 5).toFixed(2)}
            </span>
          </div>
          <div className="flex flex-col sm:flex-row gap-2">
            <Button variant="outline" className="flex-1">
              Continuar comprando
            </Button>
            <Button className="flex-1 bg-plattea1">Proceder al pago</Button>
          </div>
        </div>
      </div>
    </div>
  )
}

function MinusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
    </svg>
  )
}


function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
