/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xIyss5SI0tk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"

export function Carrusel() {
  return (
    <div className="w-screen h-screen overflow-hidden">
      <Carousel className="w-full h-full">
        <CarouselContent>
          <CarouselItem>
            <img
              src="/placeholder.svg"
              width={1920}
              height={1080}
              alt="Carousel Image 1"
              className="w-full h-full object-cover"
              style={{ aspectRatio: "1920/1080", objectFit: "cover" }}
            />
          </CarouselItem>
          <CarouselItem>
            <img
              src="/placeholder.svg"
              width={1920}
              height={1080}
              alt="Carousel Image 2"
              className="w-full h-full object-cover"
              style={{ aspectRatio: "1920/1080", objectFit: "cover" }}
            />
          </CarouselItem>
          <CarouselItem>
            <img
              src="/placeholder.svg"
              width={1920}
              height={1080}
              alt="Carousel Image 3"
              className="w-full h-full object-cover"
              style={{ aspectRatio: "1920/1080", objectFit: "cover" }}
            />
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>
    </div>
  )
}
