/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/78DqaC9Qpog
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Puntuacion } from "./puntuacion"

export function Comentariodos() {
  return (
    <Card className="p-4">
      <Puntuacion />
      <div className="flex items-start space-x-4">
        <Avatar>
          <AvatarImage src="/placeholder-user.jpg" alt="User avatar" />
          <AvatarFallback>AG</AvatarFallback>
        </Avatar>
        <div className="flex-1">
          <div className="flex items-center justify-between">
            <div>
              <h4 className="text-sm font-medium">arturo garzon gamarra</h4>
              <div className="flex items-center space-x-1 text-sm text-muted-foreground">
                <StarIcon className="w-4 h-4" />
                <StarIcon className="w-4 h-4" />
                <StarIcon className="w-4 h-4" />
                <StarIcon className="w-4 h-4" />
                <StarIcon className="w-4 h-4" />
                <span>February 4, 2024</span>
              </div>
            </div>
          </div>
          <p className="mt-2 text-sm">
            Este juego se sorprendio totalmente, It's awesome!! siento que un juego super completo, los personajes, las
            animaciones de los ulti y la historia es de no perderse, el interactuar con los personajes.. es una pasada!
            solo quiero darle las felicitaciones a los desarrolladores, a los escritores y diseñadores graficos, de
            verdad que se que nada es perfecto y que hay personas que nada les parece, pero en mi opinion el mejor
            juego.. y vaya que tengo 5 ya con este ... pero este ahora es mi favorito.
          </p>
          <div className="mt-4 text-sm text-muted-foreground">Esta opinión les resultó útil a 9 personas</div>
          <div className="mt-2 flex items-center space-x-2">
            <span className="text-sm">¿Te resultó útil?</span>
            <Button variant="outline" size="sm">
              Si
            </Button>
            <Button variant="outline" size="sm">
              No
            </Button>
          </div>
          <div className="mt-4">
            <Textarea placeholder="Agregar comentario..." className="w-full" />
            <Button variant="outline" className="mt-2">
              Publicar
            </Button>
          </div>
        </div>
      </div>
    </Card>
  )
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
