/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZjMTMD66QaX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";

export function Configuracion() {
  return (
    <Card className="mx-auto w-full max-w-3xl mt-9 mb-9">
      <CardHeader>
        <CardTitle>Configuración de Perfil</CardTitle>
        <CardDescription>Actualiza tu información de perfil.</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-6">
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="name">Nombre</Label>
            <Input id="name" placeholder="Ingresa tu nombre" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="lastName">Apellidos</Label>
            <Input id="lastName" placeholder="Ingresa tus apellidos" />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="address">Dirección</Label>
            <Input id="address" placeholder="Ingresa tu dirección" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="city">Ciudad</Label>
            <Input id="city" placeholder="Ingresa tu ciudad" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Descripción</Label>
          <Textarea
            id="description"
            placeholder="Escribe una descripción"
            className="min-h-[100px]"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="email">Correo Electrónico</Label>
          <Input
            id="email"
            type="email"
            placeholder="Ingresa tu correo electrónico"
          />
        </div>
        <div className="space-y-2">
          <Label>Editar Foto de Perfil</Label>
          <div className="flex items-center gap-4">
            <Avatar className="h-20 w-20">
              <AvatarImage src="/placeholder-user.jpg" alt="Foto de Perfil" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <Button variant="outline" asChild>
              <label htmlFor="profile-photo" className="cursor-pointer">
                Cambiar Foto
              </label>
            </Button>
            <input
              id="profile-photo"
              type="file"
              accept="image/*"
              className="hidden"
            />
          </div>
        </div>
        <div className="space-y-2">
          <Label>Editar Banner</Label>
          <div className="flex items-center gap-4">
            <img
              src="/placeholder.svg"
              alt="Banner"
              className="aspect-[5/1] w-full rounded-md object-cover"
              width="600"
              height="120"
            />
          </div>
          <Button variant="outline" asChild>
            <label htmlFor="banner-photo" className="cursor-pointer">
              Cambiar Banner
            </label>
          </Button>
          <input
            id="banner-photo"
            type="file"
            accept="image/*"
            className="hidden"
          />
        </div>
      </CardContent>
      <CardFooter className="flex justify-end gap-4">
        <Button variant="outline">Cancelar</Button>
        <Button>Guardar Cambios</Button>
      </CardFooter>
    </Card>
  );
}
