/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qr9jbHXbezq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function EditarFotoCubiculo() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Editar foto de tienda</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="flex justify-center">
          <img
            src="/placeholder.svg"
            alt="Foto de la tienda"
            width={400}
            height={300}
            className="rounded-md object-cover"
            style={{ aspectRatio: "400/300", objectFit: "cover" }}
          />
        </div>
        <div className="mt-4">
          <Label htmlFor="image">Cargar imagen</Label>
          <Input id="image" type="file" />
        </div>
      </CardContent>
      <CardFooter className="flex justify-end gap-2">
        <Button variant="outline">Cancelar</Button>
        <Button>Guardar</Button>
      </CardFooter>
    </Card>
  )
}
