/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wy8RzWyjGkH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Playfair_Display } from 'next/font/google'
import { Prata } from 'next/font/google'

playfair_display({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export function Favoritos() {
  return (
    <div className="bg-background text-foreground min-h-screen flex flex-col">
      <header className="py-6 px-4 md:px-6 border-b">
        <div className="container max-w-5xl mx-auto">
          <h1 className="text-3xl font-bold">Favoritos de Tienda</h1>
          <p className="text-muted-foreground text-sm">Guarda tus tiendas favoritas en un solo lugar.</p>
        </div>
      </header>
      <main className="flex-1 py-12 px-4 md:px-6">
        <div className="container max-w-5xl mx-auto grid gap-8">
          <div className="flex justify-between items-center">
            <div>
              <h2 className="text-2xl font-bold">Tus Tiendas Favoritas</h2>
              <p className="text-muted-foreground text-sm">Agrega o elimina tiendas de tu lista de favoritos.</p>
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <Card>
              <img
                src="/placeholder.svg"
                alt="Tienda"
                width={300}
                height={200}
                className="rounded-t-lg object-cover w-full aspect-[4/3]"
              />
              <CardContent className="p-4">
                <h3 className="text-lg font-medium">Tienda 1</h3>
                <div className="flex justify-between items-center mt-2">
                  <Button variant="ghost" size="icon">
                    <XIcon className="w-5 h-5" />
                    <span className="sr-only">Eliminar</span>
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Tienda"
                width={300}
                height={200}
                className="rounded-t-lg object-cover w-full aspect-[4/3]"
              />
              <CardContent className="p-4">
                <h3 className="text-lg font-medium">Tienda 2</h3>
                <div className="flex justify-between items-center mt-2">
                  <Button variant="ghost" size="icon">
                    <XIcon className="w-5 h-5" />
                    <span className="sr-only">Eliminar</span>
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Tienda"
                width={300}
                height={200}
                className="rounded-t-lg object-cover w-full aspect-[4/3]"
              />
              <CardContent className="p-4">
                <h3 className="text-lg font-medium">Tienda 3</h3>
                <div className="flex justify-between items-center mt-2">
                  <Button variant="ghost" size="icon">
                    <XIcon className="w-5 h-5" />
                    <span className="sr-only">Eliminar</span>
                  </Button>
                </div>
              </CardContent>
            </Card>
            <Card>
              <img
                src="/placeholder.svg"
                alt="Tienda"
                width={300}
                height={200}
                className="rounded-t-lg object-cover w-full aspect-[4/3]"
              />
              <CardContent className="p-4">
                <h3 className="text-lg font-medium">Tienda 4</h3>
                <div className="flex justify-between items-center mt-2">
                  <Button variant="ghost" size="icon">
                    <XIcon className="w-5 h-5" />
                    <span className="sr-only">Eliminar</span>
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}

function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
