/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1gwmgHCAuAP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useMemo } from "react"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { Slider } from "@/components/ui/slider"
import { Input } from "@/components/ui/input"

export function FiltroProductos() {
  const [selectedCategories, setSelectedCategories] = useState([])
  const [priceRange, setPriceRange] = useState([0, 100])
  const [sizeRange, setSizeRange] = useState([0, 20])
  const [searchTerm, setSearchTerm] = useState("")
  const products = [
    {
      id: 1,
      name: "Camiseta de algodón",
      category: "Ropa",
      price: 25,
      size: 10,
    },
    {
      id: 2,
      name: "Pantalón de mezclilla",
      category: "Ropa",
      price: 50,
      size: 12,
    },
    {
      id: 3,
      name: "Zapatos de cuero",
      category: "Calzado",
      price: 80,
      size: 8,
    },
    {
      id: 4,
      name: "Chaqueta de lana",
      category: "Ropa",
      price: 70,
      size: 14,
    },
    {
      id: 5,
      name: "Bolso de cuero",
      category: "Accesorios",
      price: 40,
      size: 6,
    },
    {
      id: 6,
      name: "Reloj de pulsera",
      category: "Accesorios",
      price: 100,
      size: 2,
    },
  ]
  const filteredProducts = useMemo(() => {
    return products.filter((product) => {
      return (
        (selectedCategories.length === 0 || selectedCategories.includes(product.category)) &&
        product.price >= priceRange[0] &&
        product.price <= priceRange[1] &&
        product.size >= sizeRange[0] &&
        product.size <= sizeRange[1] &&
        product.name.toLowerCase().includes(searchTerm.toLowerCase())
      )
    })
  }, [selectedCategories, priceRange, sizeRange, searchTerm])
  const handleCategoryChange = (category) => {
    if (selectedCategories.includes(category)) {
      setSelectedCategories(selectedCategories.filter((c) => c !== category))
    } else {
      setSelectedCategories([...selectedCategories, category])
    }
  }
  const handlePriceChange = (values) => {
    setPriceRange(values)
  }
  const handleSizeChange = (values) => {
    setSizeRange(values)
  }
  const handleSearchChange = (event) => {
    setSearchTerm(event.target.value)
  }
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-2xl font-bold mb-6">Filtrar productos</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white rounded-lg shadow-md p-6">
          <h2 className="text-lg font-bold mb-4">Categoría</h2>
          <div className="grid grid-cols-1 gap-2">
            <Label className="flex items-center gap-2">
              <Checkbox
                checked={selectedCategories.includes("Ropa")}
                onCheckedChange={() => handleCategoryChange("Ropa")}
              />
              Ropa
            </Label>
            <Label className="flex items-center gap-2">
              <Checkbox
                checked={selectedCategories.includes("Calzado")}
                onCheckedChange={() => handleCategoryChange("Calzado")}
              />
              Calzado
            </Label>
            <Label className="flex items-center gap-2">
              <Checkbox
                checked={selectedCategories.includes("Accesorios")}
                onCheckedChange={() => handleCategoryChange("Accesorios")}
              />
              Accesorios
            </Label>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6">
          <h2 className="text-lg font-bold mb-4">Precio</h2>
          <Slider min={0} max={100} step={1} value={[priceRange]} onValueChange={handlePriceChange} className="mb-4" />
          <div className="flex justify-between text-sm text-muted-foreground">
            <span>${priceRange[0]}</span>
            <span>${priceRange[1]}</span>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6">
          <h2 className="text-lg font-bold mb-4">Tamaño</h2>
          <Slider min={0} max={20} step={1} value={[sizeRange]} onValueChange={handleSizeChange} className="mb-4" />
          <div className="flex justify-between text-sm text-muted-foreground">
            <span>{sizeRange[0]}</span>
            <span>{sizeRange[1]}</span>
          </div>
        </div>
      </div>
      <div className="mt-6">
        <Input
          type="search"
          placeholder="Buscar productos..."
          value={searchTerm}
          onChange={handleSearchChange}
          className="w-full rounded-lg bg-white px-4 py-2 shadow-md"
        />
      </div>
    </div>
  )
}
