/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jT6cuUjE8JV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardDescription, CardContent } from "@/components/ui/card"
import Link from "next/link"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function HistorialPedidos() {
  return (
    <div className="w-full h-full">
      <Card className="h-full">
        <CardHeader className="px-7 md:px-10">
          <Link href="#" className="font-medium" prefetch={false}>
            Historial de Pedidos
          </Link>
          <CardDescription>
            <Link href="#" className="font-medium" prefetch={false}>
              Todos tus pedidos realizados.
            </Link>
          </CardDescription>
        </CardHeader>
        <CardContent className="h-full">
          <Table className="h-full w-full">
            <TableHeader>
              <TableRow>
                <TableHead>
                  <Link href="#" className="font-medium" prefetch={false}>
                    Fecha del Pedido
                  </Link>
                </TableHead>
                <TableHead>
                  <Link href="#" className="font-medium" prefetch={false}>
                    Número de Pedido
                  </Link>
                </TableHead>
                <TableHead>
                  <Link href="#" className="font-medium" prefetch={false}>
                    Artículos
                  </Link>
                </TableHead>
                <TableHead className="text-right">
                  <Link href="#" className="font-medium" prefetch={false}>
                    Total
                  </Link>
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow className="cursor-pointer">
                <TableCell>
                  <Link href="/historial" className="font-medium" prefetch={false}>
                    2023-06-26
                  </Link>
                </TableCell>
                <TableCell>
                  <Link href="/historial" className="font-medium" prefetch={false}>
                    INV004
                  </Link>
                </TableCell>
                <TableCell>
                  <Link href="/historial" className="font-medium" prefetch={false}>
                    Sudadera con capucha x 1
                  </Link>
                  <Link href="/historial" className="font-medium" prefetch={false}>
                    Pantalones vaqueros x 2
                  </Link>
                </TableCell>
                <TableCell className="text-right">
                  <Link href="/historial" className="font-medium" prefetch={false}>
                    $550.00
                  </Link>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
