/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cA3mbfguQVS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Baskerville } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function Perfil() {
  return (
    <div className="w-full">
      <div className="container mx-auto px-4 md:px-6 py-8 grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="bg-background rounded-lg shadow-md p-6">
          <div className="flex items-center gap-4">
            <Avatar className="h-16 w-16">
              <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <h2 className="text-xl font-bold">John Doe</h2>
              <p className="text-muted-foreground">Madrid, España</p>
            </div>
          </div>
          <p className="mt-4 text-muted-foreground">
            Soy un emprendedor apasionado por la tecnología y la innovación. Me gusta explorar nuevas ideas y llevarlas
            a la realidad.
          </p>
        </div>
        <div className="bg-background rounded-lg shadow-md p-6">
          <h2 className="text-xl font-bold mb-4">Mis Tiendas</h2>
          <div className="grid gap-4">
            <div className="bg-muted rounded-lg p-4">
              <h3 className="text-lg font-semibold">Acme Tech Store</h3>
              <p className="text-muted-foreground">Tienda de productos tecnológicos en el centro de la ciudad.</p>
              <p className="text-muted-foreground">Ubicación: Calle Mayor 123, Madrid</p>
            </div>
            <div className="bg-muted rounded-lg p-4">
              <h3 className="text-lg font-semibold">Boutique de Moda</h3>
              <p className="text-muted-foreground">Tienda de ropa y accesorios de moda.</p>
              <p className="text-muted-foreground">Ubicación: Avenida del Prado 456, Madrid</p>
            </div>
            <div className="bg-muted rounded-lg p-4">
              <h3 className="text-lg font-semibold">Librería Artesanal</h3>
              <p className="text-muted-foreground">Librería especializada en libros artesanales y de autor.</p>
              <p className="text-muted-foreground">Ubicación: Calle del Olmo 789, Madrid</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
