/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/q2RPqgx4lBy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function ProductosTienda() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 px-4 md:px-6 py-12">
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 1"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Stylish Sunglasses</h3>
          <p className="text-sm text-muted-foreground">UV protection</p>
          <h4 className="text-base font-semibold">$29.99</h4>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 2"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Leather Crossbody Bag</h3>
          <p className="text-sm text-muted-foreground">Stylish and practical</p>
          <h4 className="text-base font-semibold">$49.99</h4>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 3"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Wireless Headphones</h3>
          <p className="text-sm text-muted-foreground">High-quality sound</p>
          <h4 className="text-base font-semibold">$79.99</h4>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 4"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Classic Wristwatch</h3>
          <p className="text-sm text-muted-foreground">Timeless design</p>
          <h4 className="text-base font-semibold">$59.99</h4>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 5"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Cozy Sweater</h3>
          <p className="text-sm text-muted-foreground">Soft and warm</p>
          <h4 className="text-base font-semibold">$39.99</h4>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 6"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Sleek Backpack</h3>
          <p className="text-sm text-muted-foreground">Durable and stylish</p>
          <h4 className="text-base font-semibold">$69.99</h4>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 7"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Minimalist Wallet</h3>
          <p className="text-sm text-muted-foreground">Slim and sleek</p>
          <h4 className="text-base font-semibold">$24.99</h4>
        </div>
      </div>
      <div className="relative overflow-hidden rounded-lg group">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Product 8"
          width={400}
          height={400}
          className="object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
        />
        <div className="p-4 bg-background">
          <h3 className="text-lg font-semibold">Fitness Tracker</h3>
          <p className="text-sm text-muted-foreground">Monitor your activity</p>
          <h4 className="text-base font-semibold">$99.99</h4>
        </div>
      </div>
    </div>
  )
}
