/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wHP0OwHPRtl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function ProductosPerfil() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid max-w-5xl items-center justify-center gap-4 px-4 md:gap-8 md:px-6 lg:grid-cols-1 lg:text-left xl:max-w-6xl xl:gap-10">
        <div className="space-y-4 md:space-y-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Mis Tiendas</h2>
          </div>
        </div>
        <div className="grid w-full grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 md:gap-6 lg:gap-8">
          <div className="relative group overflow-hidden rounded-lg">
            <img
              src="/placeholder.svg"
              width={400}
              height={400}
              alt="Tienda 1"
              className="w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-110"
              style={{ aspectRatio: "400/400", objectFit: "cover" }}
            />
            <div className="absolute inset-0 bg-black/70 flex flex-col items-center justify-center text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300">
              <h3 className="text-lg font-semibold mb-2">Tienda 1</h3>
              <p className="text-sm">Descripción de la tienda 1</p>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg">
            <img
              src="/placeholder.svg"
              width={400}
              height={400}
              alt="Tienda 2"
              className="w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-110"
              style={{ aspectRatio: "400/400", objectFit: "cover" }}
            />
            <div className="absolute inset-0 bg-black/70 flex flex-col items-center justify-center text-white opacity-100 transition-opacity duration-300">
              <Link
                href="#"
                className="mt-4 bg-primary text-primary-foreground px-4 py-2 rounded-md hover:bg-primary/80"
                prefetch={false}
              >
                +
              </Link>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg" />
          <div className="relative group overflow-hidden rounded-lg" />
          <div className="relative group overflow-hidden rounded-lg" />
          <div className="relative group overflow-hidden rounded-lg" />
        </div>
      </div>
    </section>
  )
}
