/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ieuNZWRSQHC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function ResumenCompra() {
  return (
    <div className="bg-background p-6 md:p-8 lg:p-10">
      <h1 className="mb-6 text-2xl font-bold">Resumen de la compra</h1>
      <div className="overflow-hidden rounded-lg border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="hidden w-[100px] sm:table-cell"></TableHead>
              <TableHead>Producto</TableHead>
              <TableHead>Cantidad</TableHead>
              <TableHead className="hidden md:table-cell">Precio unitario</TableHead>
              <TableHead className="hidden md:table-cell">Precio total</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className="hidden sm:table-cell">
                <img
                  src="/placeholder.svg"
                  alt="Producto 1"
                  width={80}
                  height={80}
                  className="aspect-square rounded-md object-cover"
                />
              </TableCell>
              <TableCell className="font-medium">Producto 1</TableCell>
              <TableCell>2</TableCell>
              <TableCell className="hidden md:table-cell">$19.99</TableCell>
              <TableCell className="hidden md:table-cell">$39.98</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="hidden sm:table-cell">
                <img
                  src="/placeholder.svg"
                  alt="Producto 2"
                  width={80}
                  height={80}
                  className="aspect-square rounded-md object-cover"
                />
              </TableCell>
              <TableCell className="font-medium">Producto 2</TableCell>
              <TableCell>1</TableCell>
              <TableCell className="hidden md:table-cell">$29.99</TableCell>
              <TableCell className="hidden md:table-cell">$29.99</TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="hidden sm:table-cell">
                <img
                  src="/placeholder.svg"
                  alt="Producto 3"
                  width={80}
                  height={80}
                  className="aspect-square rounded-md object-cover"
                />
              </TableCell>
              <TableCell className="font-medium">Producto 3</TableCell>
              <TableCell>3</TableCell>
              <TableCell className="hidden md:table-cell">$9.99</TableCell>
              <TableCell className="hidden md:table-cell">$29.97</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
      <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">

        <Card>
          <CardHeader>
            <CardTitle>Total a pagar</CardTitle>
          </CardHeader>
          <CardContent className="text-2xl font-bold">$99.94</CardContent>
        </Card>
      </div>
      <div className="mt-6 flex justify-end">
        <Button size="lg">Confirmar compra</Button>
      </div>
    </div>
  )
}
