/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mfrMiMCYi7S
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function TiendasDestacadas() {
  return (
    <div className="container mx-auto px-4 md:px-6 lg:px-7">
        <h2 className="text-3xl font-bold mb-6 text-center">
          Tiendas Destacadas
        </h2>
    <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 p-4 md:p-6">
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">Visit Store</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Store 1"
          width={500}
          height={400}
          className="object-cover w-full h-64"
          style={{ aspectRatio: "500/400", objectFit: "cover" }}
        />
        <div className="p-4 bg-background">
          <h3 className="text-xl font-bold">Tienda de Ropa Elegante</h3>
          <p className="text-sm text-muted-foreground">Encuentra prendas de moda y de alta calidad.</p>
          <Button variant="outline" className="mt-4">
            Visitar Tienda
          </Button>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">Visit Store</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Store 2"
          width={500}
          height={400}
          className="object-cover w-full h-64"
          style={{ aspectRatio: "500/400", objectFit: "cover" }}
        />
        <div className="p-4 bg-background">
          <h3 className="text-xl font-bold">Tienda de Artesanía Local</h3>
          <p className="text-sm text-muted-foreground">Descubre piezas únicas hechas a mano.</p>
          <Button variant="outline" className="mt-4">
            Visitar Tienda
          </Button>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">Visit Store</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Store 3"
          width={500}
          height={400}
          className="object-cover w-full h-64"
          style={{ aspectRatio: "500/400", objectFit: "cover" }}
        />
        <div className="p-4 bg-background">
          <h3 className="text-xl font-bold">Tienda de Libros y Papelería</h3>
          <p className="text-sm text-muted-foreground">Encuentra tus libros y artículos de oficina favoritos.</p>
          <Button variant="outline" className="mt-4">
            Visitar Tienda
          </Button>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">Visit Store</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Store 4"
          width={500}
          height={400}
          className="object-cover w-full h-64"
          style={{ aspectRatio: "500/400", objectFit: "cover" }}
        />
        <div className="p-4 bg-background">
          <h3 className="text-xl font-bold">Tienda de Productos Naturales</h3>
          <p className="text-sm text-muted-foreground">Encuentra productos saludables y orgánicos.</p>
          <Button variant="outline" className="mt-4">
            Visitar Tienda
          </Button>
        </div>
      </div>
    </section>
    </div>
  )
}
