/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8w1v4uWOMAB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TituloTienda() {
  return (
    <div className="flex flex-col items-center justify-center py-11 md:py-10 lg:py-10">
      <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">Centered Title</h1>
    </div>
  )
}
